### PR TITLE
Add GitHub Actions release workflows

### PR DESCRIPTION
**Pull request by mnmkng**
Release guide is [in Notion](https://www.notion.so/apify/Release-Process-7f2b48c4120b4ba6b9a7b3cae6c86583).

### CODE REVIEW

**Comment by mnmkng** [comment]
Ok, got it, need to replicate this config from Travis in GitHub Actions

```
addons:
    hosts:
        - localhost-test
```

**Review by jancurn — APPROVED** [review]
Thanks @mnmkng, the deployment looks a bit complicated, but let's see.

We can try to release version 0.5.0 with this new workflow. Or perhaps call it version 1.0?

**Comment by mnmkng** [comment]
@jancurn yeah sadly actions have much more complex syntax than Travis.

But we need to fix the tests first. Dunno why they're failing now. Will check that on Monday.

**Comment by mnmkng** [comment]
@jancurn Ok, so it's a DNS resolution issue for the non-existent hostname. Not sure yet what's a proper way to fix that.
image

**Comment by jancurn** [comment]
> Ok, so it's a DNS resolution issue for the non-existent hostname. Not sure yet what's a proper way to fix that

@mnmkng The `non-existent-hostname` should test an invalid DNS resolution, not sure what is the problem, the pipeline breaks on that?

**Pull request merged**
